# Generated by Django 5.0.4 on 2024-08-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_App', '0002_account'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Accounts_Table',
        ),
    ]
